# Generated by Django 5.2.9 on 2026-01-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='user_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
