# Generated by Django 6.0 on 2026-01-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_expense_date_alter_expense_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='month_start_date',
        ),
    ]
